In [13]:
import numpy
from matplotlib import pyplot
%matplotlib inline

In [14]:
#meshgrid
x_start, x_end = -1.0, 2.0
y_start, y_start = -0.5, 0.5
N = 51
x = numpy.linspace(-1.0, 2.0, N)
y = numpy.linspace(-0.5, 0.5, N)
X, Y = numpy.meshgrid(x, y)

In [15]:
X,Y

(array([[-1.  , -0.94, -0.88, ...,  1.88,  1.94,  2.  ],
        [-1.  , -0.94, -0.88, ...,  1.88,  1.94,  2.  ],
        [-1.  , -0.94, -0.88, ...,  1.88,  1.94,  2.  ],
        ..., 
        [-1.  , -0.94, -0.88, ...,  1.88,  1.94,  2.  ],
        [-1.  , -0.94, -0.88, ...,  1.88,  1.94,  2.  ],
        [-1.  , -0.94, -0.88, ...,  1.88,  1.94,  2.  ]]),
 array([[-0.5 , -0.5 , -0.5 , ..., -0.5 , -0.5 , -0.5 ],
        [-0.48, -0.48, -0.48, ..., -0.48, -0.48, -0.48],
        [-0.46, -0.46, -0.46, ..., -0.46, -0.46, -0.46],
        ..., 
        [ 0.46,  0.46,  0.46, ...,  0.46,  0.46,  0.46],
        [ 0.48,  0.48,  0.48, ...,  0.48,  0.48,  0.48],
        [ 0.5 ,  0.5 ,  0.5 , ...,  0.5 ,  0.5 ,  0.5 ]]))

In [20]:
#import data files
x_source = numpy.loadtxt('../../AeroPython/lessons/resources/NACA0012_x.txt')
y_source = numpy.loadtxt('../../AeroPython/lessons/resources/NACA0012_y.txt')
sigma_source = numpy.loadtxt('../../AeroPython/lessons/resources/NACA0012_sigma.txt')
numpy.shape(x_source)

(100,)

In [17]:
import math

In [18]:
def get_velocity(strength, xs, ys, X, Y):
    
    u = strength/(2*numpy.pi)*(X-xs)/((X-xs)**2+(Y-ys)**2)
    v = strength/(2*numpy.pi)*(Y-ys)/((X-xs)**2+(Y-ys)**2)
    
    return u, v

In [19]:
def get_stream_function(strength, xs, ys, X, Y):
    
    psi = strength/(2*numpy.pi)*numpy.arctan2((Y-ys), (X-xs))
    
    return psi

In [21]:
#superpostion
u_source, v_source, psi_source= 0, 0, 0
for i in range(100):
    u_source1,v_source1 = get_velocity(sigma_source[i],x_source[i],y_source[i],X,Y)
    psi_source1 = get_stream_function(sigma_source[i],x_source[i],y_source[i],X,Y)
    
    u_source = u_source1+u_source
    v_source = v_source1+u_source
    psi_source = psi_source1+psi_source

In [22]:
u_source

array([[-0.00542396, -0.00569564, -0.00596639, ..., -0.00482657,
        -0.00458448, -0.004351  ],
       [-0.00560364, -0.00590372, -0.00620808, ..., -0.00498151,
        -0.004719  , -0.00446816],
       [-0.00578227, -0.00611129, -0.00645013, ..., -0.00513539,
        -0.0048522 , -0.00458389],
       ..., 
       [-0.00578227, -0.00611129, -0.00645013, ..., -0.00513539,
        -0.0048522 , -0.00458389],
       [-0.00560364, -0.00590372, -0.00620808, ..., -0.00498151,
        -0.004719  , -0.00446816],
       [-0.00542396, -0.00569564, -0.00596639, ..., -0.00482657,
        -0.00458448, -0.004351  ]])

In [23]:
v_source

array([[-0.00538742, -0.00565694, -0.00592535, ..., -0.00467509,
        -0.0044476 , -0.00422686],
       [-0.0055684 , -0.00586639, -0.00616848, ..., -0.00483326,
        -0.00458528, -0.00434711],
       [-0.00574835, -0.00607535, -0.00641199, ..., -0.00499062,
        -0.00472187, -0.00446609],
       ..., 
       [-0.00581628, -0.00614733, -0.00648837, ..., -0.00528041,
        -0.00498277, -0.00470193],
       [-0.00563897, -0.00594114, -0.00624778, ..., -0.00512999,
        -0.00485294, -0.00458944],
       [-0.0054606 , -0.00573443, -0.00600753, ..., -0.00497827,
        -0.00472158, -0.00447534]])

In [24]:
psi_source

array([[ 0.00287556,  0.00317733,  0.00351663, ...,  0.00320127,
         0.00296501,  0.00275311],
       [ 0.00276529,  0.00306134,  0.00339489, ...,  0.00310318,
         0.00287198,  0.00266492],
       [ 0.00265143,  0.00294118,  0.00326831, ...,  0.00300201,
         0.00277626,  0.00257439],
       ..., 
       [-0.00265143, -0.00294118, -0.00326831, ..., -0.00300201,
        -0.00277626, -0.00257439],
       [-0.00276529, -0.00306134, -0.00339489, ..., -0.00310318,
        -0.00287198, -0.00266492],
       [-0.00287556, -0.00317733, -0.00351663, ..., -0.00320127,
        -0.00296501, -0.00275311]])

In [25]:
#free stream
u_inf = 1.0

u_freestream = u_inf * numpy.ones((N, N))
v_freestream = numpy.zeros((N, N))